config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'index#index'

  # Cards
  get '/cards', to: 'cards#index'
  get '/cards/search', to: 'cards#search'
  get '/cards/filter/:filter(/:criteria)', to: 'cards#filter'
  get '/cards/show/:mould_id/:version', to: 'cards#show'

  # Decks
  get '/decks', to: 'decks#index'
  get '/decks/builder', to: 'decks#builder'
  get '/decks/builder/from/:id', to: 'decks#builder_from_deck_id'
  get '/decks/show/:id', to: 'decks#show'
  get '/decks/show/player/:user_id/deck/:deck_id', to: 'decks#show_player_deck'

  # Matches
  get '/matches', to: 'matches#index'
  get '/matches/show/:match_id', to: 'matches#show'

  # Player
  get '/player/:player_id', to: 'player#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
require 'zombie_battleground/browser/cards'

class CardsController < ApplicationController
  include ZombieBattleground::Browser::Cards

  def index; end

  def show
    @card = all_cards.find do |card|
      card.mould_id == params[:mould_id] &&
        card.version == params[:version]
    end
  end

  def filter
    @filter = params[:filter]
    @criteria = params[:criteria]

    @found = if @filter == 'all'
               all_cards
             else
               all_cards.select { |card| card.send(@filter) == @criteria }
             end

    render 'cards/search'
  end

  def search
    @found = []

    @normalized_terms = nomalize_search_terms
    return if @normalized_terms.blank?

    all_cards.each do |card|
      @normalized_terms.each do |term|
        next unless card.description.match?(term) ||
                    card.flavor_text.match?(term) ||
                    card.name.match?(term) ||
                    card.rank.match?(term) ||
                    card.rarity.match?(term) ||
                    card.set.match?(term) ||
                    card.kind.match?(term) ||
                    card.type.match?(term)

        @found << card
      end
    end
  end

  def nomalize_search_terms
    terms = params[:terms]
    return if terms.nil?

    terms.downcase
        .tr('_', '')
        .gsub(/[^A-Za-z]+/, '_split_')
        .split('_split_')
        .compact
        .reject { |term| term.empty? || term.length < 3 }
        .map { |term| Regexp.new(term, Regexp::IGNORECASE) }
  end
end

app/controllers/decks_controller.rb
require 'zombie_battleground/browser/cards'
require 'zombie_battleground/browser/decks'

class DecksController < ApplicationController
  include ZombieBattleground::Browser::Cards
  include ZombieBattleground::Browser::Decks

  def index; end

  def fetch_all_cards
    @all_cards = all_cards
  end

  def show
    @cards = []

    @deck = ZombieBattleground::Api.deck(id: params[:id].to_i)
    @deck_faction = ZombieBattleground::Api.deck_faction(@deck.hero_id)
    @deck.cards.each do |simple_card|
      Array.new(simple_card.amount) do
        @cards << all_cards.find { |card| card.name == simple_card.card_name }
      end
    end

    render 'decks/viewer'
  end

  def show_player_deck
    @cards = []

    @deck = ZombieBattleground::Api.decks(user_id: params[:user_id], deck_id: params[:deck_id].to_i).first
    if (@deck.nil?)
      flash[:warning] = "Deck #{params[:deck_id]} not found for #{params[:user_id]}"
      redirect_to(matches_path)
      return
    end

    @deck_faction = ZombieBattleground::Api.deck_faction(@deck.hero_id)
    @deck.cards.each do |simple_card|
      Array.new(simple_card.amount) do
        @cards << all_cards.find { |card| card.name == simple_card.card_name }
      end
    end

    render 'decks/viewer'
  end

  before_action :fetch_all_cards, only: [:builder, :builder_from_deck_id]
  def builder
    render 'decks/builder'
  end

  def builder_from_deck_id
    @cards = []

    @deck = ZombieBattleground::Api.deck(id: params[:id].to_i)
    @deck_faction = ZombieBattleground::Api.deck_faction(@deck.hero_id)
    @deck.cards.each do |simple_card|
      Array.new(simple_card.amount) do
        @cards << all_cards.find { |card| card.name == simple_card.card_name }
      end
    end

    render 'decks/builder'
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index; end
end

app/controllers/matches_controller.rb
require 'zombie_battleground/browser/matches'

class MatchesController < ApplicationController
  include ZombieBattleground::Browser::Matches

  def index
    @matches = buffered_matches.first(48)
  end

  def show
    @match = ZombieBattleground::Api.match(id: params[:match_id].to_i)
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def index
    @player_id = params[:player_id]
    @decks = ZombieBattleground::Api.decks(user_id: params[:player_id])
    @matches = ZombieBattleground::Api.matches_for_player(params[:player_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'primary' then 'alert alert-primary'
    when 'secondary' then 'alert alert-secondary'
    when 'success' then 'alert alert-success'
    when 'danger' then 'alert alert-danger'
    when 'warning' then 'alert alert-warning'
    when 'info' then 'alert alert-info'
    when 'light' then 'alert alert-light'
    when 'dark' then 'alert alert-dark'
    end
  end

  def hero_faction(hero_id)
    ZombieBattleground::Api.deck_faction(hero_id)
  end
end

app/views/cards/index.html.erb
</br>
<div class="list-group">
  <p>All Cards</p>
  <a href="/cards/filter/all" class="list-group-item list-group-item-action">All</a>
</div>
</br>
<div class="list-group">
  <p>Cards by Set</p>
  <% ZombieBattleground::Api.card_sets.each do |set| %>
  <a href="/cards/filter/set/<%= set %>" class="list-group-item list-group-item-action"><%= set.capitalize %></a>
  <% end %>
</div>
</br>
<div class="list-group">
  <p>Cards by Kind</p>
  <% ZombieBattleground::Api.card_kinds.each do |kind| %>
  <a href="/cards/filter/kind/<%= kind %>" class="list-group-item list-group-item-action"><%= kind.capitalize %></a>
  <% end %>
</div>
</br>
<div class="list-group">
  <p>Cards by Type</p>
  <% ZombieBattleground::Api.card_types.each do |type| %>
  <a href="/cards/filter/type/<%= type %>" class="list-group-item list-group-item-action"><%= type.capitalize %></a>
  <% end %>
</div>
</br>
<div class="list-group">
  <p>Cards by Rank</p>
  <% ZombieBattleground::Api.card_ranks.each do |rank| %>
  <a href="/cards/filter/rank/<%= rank %>" class="list-group-item list-group-item-action"><%= rank.capitalize %></a>
  <% end %>
</div>

app/views/cards/search.html.erb
<script>
  $(document).ready(function() {
    // make the rows clickable
    $(".clickable-thumbnail").mouseup(function(event) {
      switch(event.which) {
        case 1: // left mouse - navigate in same window
          window.location = $(this).data("href");
          break;
        case 2: // middle mouse - open in new window
          window.open($(this).data("href"));
          break;
        case 3: // right mouse - open context menu
          break;
      }
    });

    // make the search results a DataTable
    $('#searchResults').DataTable({
      // default sort by mould_id
      order: [[9, 'asc']],
      // preserve browser location
      stateSave: true,
      // look decent-ish on mobile
      responsive: true,
      // put the page nav bar on top and bottom
      dom: "<'row'<'col-sm-3'l><'col-sm-3'f><'col-sm-6'p>><'row'<'col-sm-12'tr>><'row'<'col-sm-5'i><'col-sm-7'p>>",
      // toggle the hover over tooltip on the card images
      drawCallback: function() {
        if (!("ontouchstart" in window || window.DocumentTouch && document instanceof DocumentTouch)) {
          $('[data-toggle="tooltip"]').tooltip();
        }
      }
    });
  });
</script>

</br>
<table id="searchResults" class="table table-striped table-hover table-responsive dt-responsive display nowrap">
  <caption>
  <% if @filter == 'all' %>
    All cards
  <% elsif @criteria.nil? %>
    Found cards matching: <%= @normalized_terms.map(&:to_s) %>
  <% else %>
    Found cards for: <%= @criteria %>
  <% end %>
  </caption>
  <thead>
    <tr>
      <th>View</th>
      <th>Name</th>
      <th>Set</th>
      <th>Kind</th>
      <th>Type</th>
      <th>Rank</th>
      <th>Cost</th>
      <th>Health</th>
      <th>Damage</th>
      <th>Mould ID</th>
      <th>Version</th>
    </tr>
  </thead>
  <tbody>
  <% @found.each do |found| %>
  <tr>
    <td>
      <img
        class="clickable-thumbnail img-thumbnail"
        style="cursor: pointer;"
        data-href="/cards/show/<%= found.mould_id %>/<%= found.version %>"
        src="<%= found.image_url %>"
        data-toggle="tooltip"
        data-placement="right"
        title="<%= found.flavor_text %>"
        onerror="this.src='<%= image_url("missing-card.svg") %>';"
      >
    </td>
    <td><%= found.name %></td>
    <td><%= found.set %></td>
    <td><%= found.kind %></td>
    <td><%= found.type %></td>
    <td><%= found.rank %></td>
    <td><%= found.cost %></td>
    <td><%= found.health %></td>
    <td><%= found.damage %></td>
    <td><%= found.mould_id %></td>
    <td><%= found.version %></td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/cards/show.html.erb
<script>
  $(document).ready(function() {
    // hover over flavor text
    $(function () {
      $('[data-toggle="tooltip"]').tooltip();
    })
  });
</script>

</br>

<div class="text-center">
  <img
    src="<%= @card.image_url %>"
    class="img-fluid"
    data-toggle="tooltip"
    data-placement="right"
    title="<%= @card.flavor_text %>"
    onerror="this.src='<%= image_url("missing-card.svg") %>';"
  >
</div>

</br>

<h3 class="text-center">API Details</h3>

<table class="table">
  <tr>
    <th>ID</th>
    <td><%= @card.id %></td>
  </tr>
  <tr>
    <th>Mould ID</th>
    <td><%= @card.mould_id %></td>
  </tr>
  <tr>
    <th>Version</th>
    <td><%= @card.version %></td>
  </tr>
  <tr>
    <th>Set</th>
    <td><%= @card.set %></td>
  </tr>
  <tr>
    <th>Name</th>
    <td><%= @card.name %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= @card.description %></td>
  </tr>
  <tr>
    <th>Flavor Text</th>
    <td><%= @card.flavor_text %></td>
  </tr>
  <tr>
    <th>Rank</th>
    <td><%= @card.rank %></td>
  </tr>
  <tr>
    <th>Type</th>
    <td><%= @card.type %></td>
  </tr>
  <tr>
    <th>Damage</th>
    <td><%= @card.damage %></td>
  </tr>
  <tr>
    <th>Health</th>
    <td><%= @card.health %></td>
  </tr>
  <tr>
    <th>Cost</th>
    <td><%= @card.cost %></td>
  </tr>
  <tr>
    <th>Ability</th>
    <td><%= @card.ability %></td>
  </tr>
</table>

app/views/decks/_cards_selector.html.erb
<script>
  $(document).ready(function() {
    // make the search results a DataTable
    $('#all_cards').DataTable({
      // default sort by mould_id
      order: [[9, 'asc']],
      // preserve browser location
      stateSave: true,
      // look decent-ish on mobile
      responsive: true,
      drawCallback: function() {
        if (!("ontouchstart" in window || window.DocumentTouch && document instanceof DocumentTouch)) {
          $('[data-toggle="tooltip"]').tooltip();
        }
      }
    });
  });
</script>

<p class="lead"><small class="text-muted">To do: </small>Hero/Faction chooser here, which restricts cards</p>

<p class="lead"><small class="text-muted">To do: </small>I want to add several checkboxes for fast filtering here</p>

</br>
<table id="all_cards" class="table table-striped table-hover table-responsive dt-responsive display nowrap">
  <thead>
    <tr>
      <th>View</th>
      <th>Name</th>
      <th>Set</th>
      <th>Kind</th>
      <th>Type</th>
      <th>Rank</th>
      <th>Cost</th>
      <th>Health</th>
      <th>Damage</th>
      <th>Mould ID</th>
      <th>Version</th>
    </tr>
  </thead>
  <tbody>
  <% @all_cards.each do |card| %>
  <tr>
    <td>
      <a href="#" class="modal-pop">
        <img
          class="img-thumbnail"
          src="<%= card.image_url %>"
          card-mould_id="<%= card.mould_id %>"
          card-version="<%= card.version %>"
          card-name="<%= card.name %>"
          data-toggle="tooltip"
          data-placement="bottom"
          title="<%= card.name %>"
          onerror="this.src='<%= image_url("missing-card.svg") %>';"
        >
      </a>
    </td>
    <td><%= card.name %></td>
    <td><%= card.set %></td>
    <td><%= card.kind %></td>
    <td><%= card.type %></td>
    <td><%= card.rank %></td>
    <td><%= card.cost %></td>
    <td><%= card.health %></td>
    <td><%= card.damage %></td>
    <td><%= card.mould_id %></td>
    <td><%= card.version %></td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/decks/_deck_panel.html.erb
<script>
  // These conditions need to be broken out into methods with sane line counts and
  // branching logic. Definitely not done

  $(document).ready(function() {
    // toggle tooltips on
    if (!("ontouchstart" in window || window.DocumentTouch && document instanceof DocumentTouch)) {
      $('[data-toggle="tooltip"]').tooltip();
    }
  });

  // setup the pop up card image
  $(function() {
    $('.modal-pop').on('click', function(event) {
      event.preventDefault();
      mould_id = $(this).find('img').attr('card-mould_id');
      version = $(this).find('img').attr('card-version');
      name = $(this).find('img').attr('card-name');
      $('.card-image-modal').attr('src', $(this).find('img').attr('src'));
      $('.card-details').attr('href', `/cards/show/${mould_id}/${version}`);
      $('#card-image-modal').modal('show');

      if (window.location.pathname.startsWith('/decks/builder')) {
        console.log(event.target.id);
        if (event.target.id.startsWith('card-')) {
          document.getElementById('add-card').style.display = 'none';
          document.getElementById('remove-card').style.display = '';
        } else {
          document.getElementById('add-card').style.display = '';
          document.getElementById('remove-card').style.display = 'none';
        }
      } else {
        document.getElementById('add-card').style.display = 'none';
        document.getElementById('remove-card').style.display = 'none';
      }

      if (name == 'undefined') {
        $('.card-details').prop('disabled', true);
        $('.card-details').addClass('disabled');
        $('.card-name').text('Add a new card below');
        document.getElementById('add-card').style.display = 'none';
        document.getElementById('remove-card').style.display = 'none';
      } else {
        $('.card-details').prop('disabled', false);
        $('.card-details').removeClass('disabled');
        $('.card-name').text(name);
      }
    });
  });

  var allCards = <%= @all_cards.to_json.html_safe %>;
  <% if @cards.nil? %>
  var deckCards = <%= Array.new(30).to_json.html_safe %>;
  var heroFaction = null;
  <% else %>
  var deckCards = <%= @cards.to_json.html_safe %>;
  var heroFaction = "<%= @deck_faction %>";
  <% end %>
</script>

<style>
.col-1dot2,
.col-sm-1dot2,
.col-md-1dot2,
.col-lg-1dot2,
.col-xl-1dot2 {
  position: relative;
  width: 100%;
  min-height: 1px;
  padding-right: 15px;
  padding-left: 15px;
}

.col-1dot2 {
  -webkit-box-flex: 0;
  -ms-flex: 0 0 10%;
  flex: 0 0 10%;
  max-width: 10%;
}

@media (min-width: 300px) {
  .modal-dialog {
    width: 95%;
    height: 92%;
    padding: 0;
    max-width: 380px;
    min-height: 500px;
    max-height: 600px;
  }

  .modal-content {
    height: 99%;
  }

  .col-1dot2 {
    -webkit-box-flex: 0;
    -ms-flex: 0 0 33%;
    flex: 0 0 33%;
    max-width: 33%;
  }
}

@media (min-width: 576px) {
  .col-1dot2 {
    -webkit-box-flex: 0;
    -ms-flex: 0 0 25%;
    flex: 0 0 25%;
    max-width: 25%;
  }

  .modal-dialog {
    width: 500px;
  }
}

@media (min-width: 768px) {
  .col-1dot2 {
    -webkit-box-flex: 0;
    -ms-flex: 0 0 20%;
    flex: 0 0 20%;
    max-width: 20%;
  }

  .modal-dialog {
    width: 500px;
  }
}

@media (min-width: 992px) {
  .col-1dot2 {
    -webkit-box-flex: 0;
    -ms-flex: 0 0 16%;
    flex: 0 0 16%;
    max-width: 16%;
  }

  .modal-dialog {
    width: 500px;
  }
}

@media (min-width: 1200px) {
  .col-1dot2 {
    -webkit-box-flex: 0;
    -ms-flex: 0 0 10%;
    flex: 0 0 10%;
    max-width: 10%;
  }

  .modal-dialog {
    width: 500px;
  }
}
</style>

<div class="row">
  <% Array.new(30) do |card_place| %>
  <% if @cards.nil? %>
  <div class="col-1dot2 py-2">
    <div class="card">
      <a href="#" class="modal-pop">
        <img
          id="card-<%= card_place %>"
          class="card-img-top zbg-card-image"
          src="<%= image_url("empty-card.svg") %>"
          card-mould_id="null"
          card-version="null"
          card-name="null"
          card-empty="true"
          data-toggle="tooltip"
          data-placement="bottom"
          title="Add a card below"
        >
      </a>
    </div>
  </div>
  <% else %>
  <% card = @cards[card_place] %>
  <div class="col-1dot2 py-2">
    <div class="card">
      <a href="#" class="modal-pop">
        <img
          id="card-<%= card_place %>"
          class="card-img-top zbg-card-image"
          src="<%= card.image_url %>"
          card-mould_id="<%= card.mould_id %>"
          card-version="<%= card.version %>"
          card-name="<%= card.name %>"
          card-empty="false"
          data-toggle="tooltip"
          data-placement="bottom"
          title="<%= card.name %>"
          onerror="this.src='<%= image_url("missing-card.svg") %>';"
        >
      </a>
    </div>
  </div>
  <% end %>
  <% end %>
</div>

<div class="modal" id="card-image-modal" tabindex="-1" role="dialog" aria-labelledby="card-image-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <p class="lead card-name mr-auto"></p>
        <img
          src=""
          class="card-image-modal"
          style="width: 100%;"
        >
      </div>
      <div class="modal-footer">
        <button id="remove-card" class="btn btn-danger mr-auto">Remove</button>
        <button id="add-card" class="btn btn-success mr-auto">Add</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="" class="card-details btn btn-info" target="_blank">Card Details</a>
      </div>
    </div>
  </div>
</div>

app/views/decks/builder.html.erb
</br>
<h2 class="text-center">Deck Builder</h2>

<p class="lead">This is work in progress, Add/Remove buttons don't work yet</p>

<%= render('decks/deck_panel') %>
<%= render('decks/cards_selector') %>

app/views/decks/index.html.erb
</br>
<div class="list-group">
  <p>Viewer (Requires a deck ID. I'm working on a deck lister/match result link to)</p>
  <a href="/decks/show/1892" class="list-group-item list-group-item-action">View Deck 1892</a>
</div>

</br>
<div class="list-group">
  <p>Builder (Doesn't work)</p>
  <a href="/decks/builder" class="list-group-item list-group-item-action">Deck Builder</a>
</div>

<br>
<div class="list-group">
  <p>While I figure how I want to make the deck builder work, here's an existing deck in the builder</p>
  <a href="/decks/builder/from/1892" class="list-group-item list-group-item-action">Deck Builder with Deck 1892</a>
</div>

app/views/decks/viewer.html.erb
</br>
<h2 class="text-center">"<%= @deck.name %>" - Deck ID <%= @deck.id %></h2>
<h4 class="text-center"> - <a href="/player/<%= @deck.user_id %>"><%= @deck.user_id %></a></h2>

<a href="/decks/builder/from/<%= @deck.id %>"><h3 class="text-center">Load in Deck Builder</h3></a>

</br>
<h5 class="text-center">To do: Make this more presentable... (and figure out how to translate abilities)</h5>
</br>
<p class="text-center">Deck Faction: <%= @deck_faction %></p>
<p class="text-center">Hero Ability Primary: <%= @deck.primary_skill_id %></p>
<p class="text-center">Hero Ability Secondary: <%= @deck.secondary_skill_id %></p>

<%= render('decks/deck_panel') %>

app/views/index/index.html.erb
<h1>Work in Progress <small class="text-muted">stuff totally works though</small></h1>

<p>
<h3>Check out Cards!</h3>

<p>
Fuzzy search works, too.

<p>
<h3>Check out Decks!</h3>

<p>
The deck builder isn't working yet, but you can load deck cards and decks by player from matches.

<p>
<h3>Checkout Matches!</h3>

<p>
Matches landing page isn't the best in my opinion, but you can view recent matches now. I'm trying to find a better presentation

<h2>To do checklist</h2>
<p>
I think I have enough tooling to start writing background threads to do card/deck/match analystics for "most winningest card", "most winningest player", "player most likely to deny matches", "winningest number of items in deck", "winningest hero ability", "winningest hero faction", etc.

<p>
Deck builder <small class="text-muted">duh</small>. I got distracted with finding the cards used in recent matches.

<p>
Deck searching by player id or fuzzy name match

<p>
Better Matches index page presentation, carousel is annoying me now.

<p>
Player scoped landing page? See player win ratio per deck and over all, player's recent matches and player's decks

<p>
Determine how to translate hero ability numbers to text

<p>
Some kind of ring buffer to keep recent matches and decks constantly updating instead of large, unnecessary batch calls to refresh all known objects

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZombieBattleground Browser</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#222">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/darkly/bootstrap.min.css" rel="stylesheet" integrity="sha384-w+8Gqjk9Cuo6XH9HKHG5t5I1VR4YBNdPt/29vwgfZR485eoEJZ8rJRbm3TR32P6k" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timeago/1.6.5/jquery.timeago.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">ZombieBattleground Browser</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor03">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/cards">Cards</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/decks">Decks</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/matches">Matches</a>
            </li>
          </ul>
          <%= form_tag cards_search_path, method: 'get', class: "form-inline my-2 my-lg-0" do %>
            <%= text_field_tag :terms, nil, placeholder: "Fuzzy Search Cards", class: "form-control mr-sm-2" %>
            <%= submit_tag 'Search', class: "btn btn-secondary my-2 my-sm-0" %>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
      </br>
      <div class="<%= flash_class(key) %>" role="alert">
        <%= value %>
      </div>
      <% end %>
      <%= yield %>
    </br>
    </div>
  </body>
</html>

app/views/matches/index.html.erb
<script>
  $(document).ready(function() {
    jQuery("time.timeago").timeago();

    $(function () {
      $('[data-toggle="tooltip"]').tooltip();
    })
  });
</script>

</br>
<h1 class="text-center">Recent Matches</h1>
<div class="row">
<% @matches.each do |match| %>
  <div class="col-sm-6 col-md-4 col-lg-3 py-2">
    <div class="card">
      <div class="card card-body h-100">
        <h5 class="card-title">Match ID <%= match.id %></h5>
        <p class="card-text">Status: <%= match.status %></p>
        <p class="card-text">Updated: <time class="timeago" datetime="<%= match.updated_at.iso8601 %>"></p>
        <% if %[Started Playing].include?(match.status) %>
        <span data-toggle="tooltip" title="Match in progess">
        <a href="/matches/show/<%= match.id %>" class="btn btn-primary disabled w-100" disabled>Match Details</a>
        </span>
        <% else %>
        <a href="/matches/show/<%= match.id %>" class="btn btn-primary">Match Details</a>
        <% end %>
        <p>
        <div class="btn-toolbar justify-content-between">
          <a href="/player/<%= match.player1_id %>" class="btn btn-primary">Player 1</a>
          <a href="/player/<%= match.player2_id %>" class="btn btn-primary float-right">Player 2</a>
        </div>
        <p>
        <div class="btn-toolbar justify-content-between">
          <a href="/decks/show/player/<%= match.player1_id %>/deck/<%= match.player1_deck_id %>" class="btn btn-sm btn-primary">P1 Deck</a>
          <a href="/decks/show/player/<%= match.player2_id %>/deck/<%= match.player2_deck_id %>" class="btn btn-sm btn-primary float-right">P2 Deck</a>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>